name: tmeroom-SFUserver CI / CD with Node

on:
  push:
    branches: ['main']

jobs:
  # ì°¸ê³  ì‚¬ì´íŠ¸
  # https://docs.github.com/ko/actions/publishing-packages/publishing-docker-images
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      
      # github actionì˜ ê°€ìƒí™˜ê²½ì— ë‚´ í”„ë¡œì íŠ¸ë¥¼ ì²´í¬ì•„ì›ƒí•˜ê¸°
      - name: Checkout
        uses: actions/checkout@v3
        
      # Github Secretê³¼ local env ì— ì €ì¥ëœ ê°’ ë¶ˆëŸ¬ì˜¤ê¸°
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tmeroom-sfu
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

# TODO: ArgoCD ê°€ ì°¸ê³ í•  ì¿ ë²„ë„¤í‹°ìŠ¤ ë°°í¬ yaml íŒŒì¼ ì‘ì„±í•˜ê³  í’€ì–´ì•¼í•¨. 
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: push_to_registry
  #   steps:

  #     # github actionì˜ IPê°€ ìˆ˜ì‹œë¡œ ë°”ë€Œë¯€ë¡œ
  #     # ê·¸ ipë¥¼ ec2ì˜ ì¸ë°”ìš´ë“œ ê·œì¹™ì—ì„œ í—ˆìš©í•´ì•¼ í•˜ë¯€ë¡œ
  #     # github actionì˜ IPë¥¼ ì–»ì–´ì˜¨ë‹¤.
  #     - name: Get Github Actions IP
  #       id: ip
  #       uses: haythem/public-ip@v1.3

  #     # ec2 IAM ê³„ì •ì˜ access key, secret keyì˜ ê³„ì •ì •ë³´ ë“±ë¡
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ap-northeast-2
          
  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v1

  #     - name: Checkout for Kustomize repository
  #       uses: actions/checkout@v2
  #       with:
  #         # kubernetes yaml íŒŒì¼ ì €ì¥
  #         repository: TeamyRoom/TMeRoom-k8s-manifest # k8s yaml íŒŒì¼ì´ ìˆëŠ” repo
  #         ref: main  # branch ì´ë¦„
  #         token: ${{ secrets.ACTION_TOKEN }} # Github Action tokenì„ ë°œê¸‰ë°›ì•„ì„œ repo secrectì— ë“±ë¡í•´ì¤˜ì•¼í•œë‹¤
  #         path: TMeRoom-k8s-manifest # ìµœìƒìœ„ ê²½ë¡œë¡œ repositoryì™€ ë™ì¼í•˜ê²Œ ì„¤ì •

  #         # ìƒˆ ì´ë¯¸ì§€ ë²„ì „ìœ¼ë¡œ íŒŒì¼ì˜ íƒœê·¸ê°’ ìˆ˜ì •
  #         # cd path ìˆ˜ì •
  #         # kustomizeë¡œ image tag ê°’ ë³€ê²½
  #     - name: Update Kubernetes resources
  #       run: |
  #         pwd
  #         ls
  #         cd TMeRoom-k8s-manifest/overlays/prd/ 
  #         kustomize edit set image ${{ steps.login-ecr.outputs.registry }}/tmeroom-sfu=${{ steps.login-ecr.outputs.registry }}/tmeroom-sfu:${{ github.run_number }}
  #         cat kustomization.yaml
  #     # ìˆ˜ì •ëœ kustomization.yaml íŒŒì¼ commit push
  #     - name: Commit and Push manfiest files
  #       uses: EndBug/add-and-commit@v9
  #       with:
  #         author_name: yslee96
  #         author_email: dbstn322@gmail.com
  #         message: "ğŸ”§   : SFU ì„œë²„ ì´ë¯¸ì§€ íƒœê·¸ ì—…ë°ì´íŠ¸ #${{ github.run_number }}"
  #         cwd: './TMeRoom-k8s-manifest'
  #         push: true

  #     # ì—…ë¡œë“œí•œ artifactsë¥¼ ì‚­ì œí•˜ê¸°
  #     - name: Remove Github Actions Artifacts
  #       if : always()
  #       uses: GeekyEggo/delete-artifact@v2.0.0
  #       with:
  #         # The name of the artifact to delete; multiple names can be supplied on new lines.
  #         name: |
  #           front-env
  #           front-nginx
  #           build-result
  #           Dockerfile
